{% set name = "drawSvg" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cduck/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 54083da6a25ac423db3e5a216e8ad37ee0393a978dd0018318f835e1bea1179f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - drawsvg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cduck/drawSvg
  summary: Library for programmatically generating SVG images
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
