{% set name = "drawSvg" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cduck/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2ded625da44020a414493e6a7fa4e67354e6bb7968e35d89afe7af2e74939b9e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - drawsvg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cduck/drawSvg
  summary: Library for programmatically generating SVG images
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
